@isTest
public class PlatformSetupFormPDFExtTest {
	/* This test is obsolete.  Prepare for class deletion.
	static testMethod void getMarketedProducts_should_list()
	{
		List<Schema.PicklistEntry> pickList = Opportunity.Marketed_Products__c.getDescribe().getPicklistValues();
		PlatformSetupFormPDFExt ext = new PlatformSetupFormPDFExt();
		ext.enrollmentOpp = new Opportunity( 
			Marketed_Products__c = pickList.get(0).getValue() + ';' + pickList.get(1).getValue()
		);

		List<string> products = ext.getMarketedProducts();

		System.assert(products.size() == 2);
	}
*/
}