public class ProductClaim {
    
    public String 	ClaimNumber			{get;set;}
    public String 	CustomerNumber		{get;set;}
    public String 	SSN					{get;set;}
    public String 	PolicyNumber		{get;set;}
    public String 	ProductCode			{get;set;}
    public String 	ClaimsIncurredDate	{get;set;}
    public String	EOBDate				{get;set;}
    public Decimal 	PaidAmount			{get;set;}
    public String  	ClaimStatusId		{get;set;}
    public String 	ClaimStatus			{get;set;}
    public String 	EOBStatus			{get;set;}
    public String 	EOBStatusID			{get;set;}
    
    public ProductClaim()
    {
        
    }

}